config/routes.rb
Omrails::Application.routes.draw do
  

  
  
 post '/tinymce_assets' => 'tinymce_assets#create'

  get "profile/place"
  get "profile/bio"
  get "users/show"

resources :posts, :path => "news" do
   member do
    post "sort" => "comments#sort"
  end
   member do
    get 'question_form'
  end
   collection { post :sort }
  member do
      put :upvote
    end
    resources :events
  resources :comments, :path => "q" do
    member do
      put :upvote
      get :tag
    end
    member do 
      get :unansweredquestions
    end
  end 
  resources :pictures
end
      
resources :comments, :path => "q" do
    member do
      put :upvote
    end
    resources :questions, :path => "a" do
    member do
      put :upvote
    end
  end
end 

 resources :events do
 resources :articles
end

resources :questions, :path => "a" do
  member do
      put :upvote
    end
   resources :links do
    member do
      put :upvote
    end
  end
end

devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :omniauth_providers => [:twitter],
controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: :registrations, sessions: "sessions"}
   
  
  root to: 'posts#index'
  match '/about', to: 'pages#about',  via:'get'
  match '/contact', to: 'pages#contact',  via:'get'
  match '/guidelines', to: 'pages#guidelines',  via:'get'
  match '/tos', to: 'pages#tos',  via:'get'
  match '/browser', to: 'pages#browser',  via:'get'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'tags/:tag', to: 'posts#show'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/upvoted', to: 'users#upvoted', as: :upvoted
  get 'users/:id/userquestions', to: 'users#questions', as: :userquestions
  get 'users/:id/notifications', to: 'users#notifications', as: :notifications 
  get 'users/:id/allnotifications', to: 'users#allnotifications', as: :allnotifications 
  post 'users/read_all_notifications', to: 'users#read_all_notification', as: :read_all_notifications 
  get 'users/:id/upvotes', to: 'users#upvotes', as: :upvotes
  get 'users/:id/allanswers', to: 'users#allanswers', as: :allanswers
  get 'users/:id/allcomments', to: 'users#allcomments', as: :allcomments
  get 'news/:id/topquestions', to: 'posts#showtopquestion', as: :topquestions
  get 'news/:id/answersmore', to: 'posts#showanswersmore', as: :answersmore
  get 'news/:id/ordered', to: 'posts#ordered', as: :ordered
  get 'news/:id/new_posts', to: 'posts#new_posts', as: :new_posts
  get 'comments/:id/unpublished', to: 'comments#unpublished', as: :unpublished
  get '/admin', to: 'posts#admin', as: :admin
  get '/admin/questions', to: 'pages#admin_questions', as: :adminquestions
  get '/admin/answers', to: 'pages#admin_answers', as: :adminanswers
  get '/admin/replies', to: 'pages#admin_replies', as: :adminreplies
  get '/following', to: 'pages#following', as: :following
  get 'top', to: 'posts#top', as: :top
  get  '/image_form', to: 'posts#image_form', as: :image_form
  get  '/search-news', to: 'posts#search', as: :search

   devise_scope :user do
    get "/info" => "registrations#info"
  end

  get '*path' => redirect('/')

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
extend FriendlyId
friendly_id :name, use: :slugged

include PublicActivity::Model
tracked only: :create, owner: ->(controller, model) { controller && controller.current_user }
tracked only: :create, recipient: ->(controller, model) { model && model }



has_attached_file :image, :styles => { :thumb => "60x60>", :original => '200x200>' }
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  has_many :posts
  has_many :comments
  has_many :questions
  has_many :pictures
  has_many :answers   
  has_many :links
  acts_as_voter  

  validates :name, presence: true
  validates_confirmation_of :password
  validates_uniqueness_of :name
  
 def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.twitter = auth.info.nickname
    user.image = URI.parse(auth.info.image.sub("_normal", "")) if auth.info.image?
  end
end

def portrait(size)

    # Twitter
    # mini (24x24)                                                                  
    # normal (48x48)                                            
    # bigger (73x73)                                                
    # original (variable width x variable height)

    if self.image.include? "twimg"

        # determine filetype        
        case 
        when self.image.downcase.include?(".jpeg")
            filetype = ".jpeg"
        when self.image.downcase.include?(".jpg")
            filetype = ".jpg"
        when self.image.downcase.include?(".gif")
            filetype = ".gif"
        when self.image.downcase.include?(".png")
            filetype = ".png"
        else
            raise "Unable to read filetype of Twitter image for User ##{self.id}"
        end

        # return requested size
        if size == "original"
            return self.image
        else
            return self.image.gsub(filetype, "_#{size}#{filetype}")
        end

    end

end


def self.new_with_session(params, session)
  if session["devise.user_attributes"]
    new session["devise.user_attributes"] do |user|
      user.attributes = params
      user.valid?
    end
  else
    super
  end
end

def password_required?
  false
end

def email_required?
  super && provider.blank?
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
after_action :read_all_notification, only: [:notifications]


  def show
 
  @user = User.friendly.find(params[:id])
  @questions = @user.get_voted Question .order("created_at desc")
  @upvoted_posts = @user.get_voted Comment .order("created_at desc")
  @comments = @user.questions.order("created_at desc")
  @links = @user.links.order("created_at desc")
  end



  def allanswers
  
  @user = User.friendly.find(params[:id])
  @comments = @user.questions.order("created_at desc").page(params[:page]).per_page(3)
  @questions = @user.get_voted Question
  @links = @user.links.order("created_at desc")
  end

 def allcomments
  
  @user = User.friendly.find(params[:id])
  @links = @user.links.order("created_at desc").page(params[:page]).per_page(10)
  @comments = @user.questions.order("created_at desc")
  @questions = @user.get_voted Question
  end


  def notifications 
  @user = User.friendly.find(params[:id]) 
  render_forbidden and return unless can_edit?
  @activities = PublicActivity::Activity.order("created_at desc").where(recipient_id: current_user.id).where(:read => false)
  @notification_count = @activities.where(:read => false)
  
  end

   def read_all_notification
   PublicActivity::Activity.where(recipient_id: current_user.id).update_all(:read => true)
  end   

   def allnotifications 
    @user = User.friendly.find(params[:id])
    render_forbidden and return unless can_edit?
  @allnotifications = PublicActivity::Activity.order("created_at desc").where(recipient_id: current_user.id).page(params[:page]).per_page(15)
  
  respond_to do |format|
          format.html
          format.js #-> will call /app/views/users/index.js.erb
  end
  
  end


 private

    def can_edit?
     current_user == @user
    end
  

  

end

app/helpers/users_helper.rb
module UsersHelper

def resource
    @resource ||= current_user
  end



end

app/views/users/_posts_show.html.erb
<% @upvoted_posts.each_with_index  do |comment, i| %>


<%= link_to (comment.post.title), post_path(comment.post) %>

<%= render 'comments/post_feed' %>


<% end %>

app/views/users/_profile_head.html.erb
<div class="sidebar-profile-nav">



<div class="avatar-border">
<div class="userprofileimage-image">
 <%= image_tag @user.image %>
</div>
</div>



<div class="userprofileimage-name">
<%= @user.name %>
</div>

<div class="userprofileimage-username">
<i class="fa fa-twitter" style="color: #288bff; font-size: 18px; display: inline-block; margin-right: 4px;"></i> 
@nevanwhiteside
<% if @user.twitter.present? %> 
<%= link_to truncate('@nevanwhiteside', length:10), "http://www.twitter.com/", :target => "_blank", style: "color: #288bff !important;" %>
<% end %>
</div>

<% if @user.place.present? %>  
<div class="userprofileimage-username">
<i class="fa fa-map-marker"></i> 
<%= @user.place %>
</div>
<% end %>



<% if current_user == @user %>

<hr style="margin-bottom: 15px;"/>
<i class="material-icons profile-settings" id="blue-edit-profile">settings</i>


<div class="fullpage-modal-container">  

  <div class="fullpage-modal" style="display: none;">
<button type="button" class="close-modal-slide" data-dismiss="modal" aria-hidden="true">×</button>
<hr class="modalline-slide" style="margin-top: 0px"/>
 <%= render :partial => "devise/registrations/edit" %>
</div>
</div>

<% end %>







</div>







 

app/views/users/_show.html.erb
<% @questions.group_by {|q| q.comment.post}.take(5).each_with_index do |(post, questions), i| %>








<% if i == 0 %>


<div class="dividerhead">
MORE FROM <%= link_to (post.title), post_path(post) %>
</div>

<div class="event-orangeHead"></div>

<div class="userprofile-event">
<%= link_to (post.title), post_path(post) %>
<div class="timeline-description" style='line-height: 1.45;'>
  <%= truncate(post.description, :separator => ' ', length: 110) %>  
</div>
</div>



<% else %>

<% if i == 1 %>
<hr class='dividerline'/>
<div class="dividerhead">
ALL RECOMMENDED
</div>
<% end %>

<div class="event-orangeHead"></div>


<% if post.pictures.present? %>
<div class="home-feed-image" style='background-image: url(<%= post.pictures.first.image %>)'>
<% else %>
<div>
<% end %>


<div class="darker" style="opacity: 0.2;"></div>

</div>

<div class="userprofile-event" style="color: #018bc6; font-size: 16px; display: inline-block;  overflow: hidden;">
<%= link_to (post.title), post_path(post), class: "blue" %>
<div class="timeline-description" style='line-height: 1.45; color: rgba(51,51,51,0.75); margin-right: 40px;'>
  <%= truncate(post.description, :separator => ' ', length: 110) %>  
</div>



<hr class="linelinks" style="margin-top: 15px; margin-bottom: 0px; width: 30%;"/>

</div>

<div class="row"></div>
<div style="margin-top: 10px;"></div>

</div>





<% end %>


 
<% for question in questions %>

<%= render :partial => 'layouts/answersfeed', locals: {question:question} %>

<hr class="line30"/>

<% end %>



<% end %>

<% if @questions.count > 5 %>
<div class="end-page-circle"></div>
<div class="end-page-circle-small"></div>
<div class="row"></div>
<% end %>

app/views/users/allanswers.html.erb
<%= render 'profile_head' %>


<div class="navbar-profile-content-container">


<div class="width7">


<div style="margin-top: 35px;"></div>



<%= link_to user_path(@user) do %>
<div class="profile-post-types">
Recommended
</div>
<% end %>

<%= link_to allcomments_path(@user) do %>
<div class="profile-post-types">
Posts
</div>
<% end %>

<div class="profile-post-types" style="color: #288bff;">
Replies & Answers
</div>

<hr style="margin-top: 20px;"/>





<div class="width5-center">


<div style="display: none;">

<div id="products">
<%= render 'users/allanswers' %>
</div>
<%= will_paginate @comments %>
</div>

</div>
</div>

</div>

app/views/users/allanswers.js.erb
$('#products').append('<%= j render('users/allanswers') %>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@comments) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/users/allcomments.html.erb
<%= render 'profile_head' %>


<div class="navbar-profile-content-container">


<div class="width7">


<div style="margin-top: 35px;"></div>


<%= link_to user_path(@user) do %>
<div class="profile-post-types">
Recommended
</div>
<% end %>

<div class="profile-post-types" style="color: #288bff;">
Posts
</div>

<%= link_to allanswers_path(@user) do %>
<div class="profile-post-types">
Replies & Answers
</div>
<% end %>

<hr style="margin-top: 20px;"/>





<div class="width5-center">



<div id="products">
<%= render 'users/allcomments' %>
</div>
<%= will_paginate @links %>



</div>
</div>

</div>

app/views/users/allcomments.js.erb
$('#products').append('<%= j render('users/allcomments') %>');
<% if @links.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@links) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/users/allnotifications.html.erb
<div style="background-color: rgba(51,51,51,0.1); padding: 25px 0px 30px 0px; line-height: 1;">
<div class="width7">
<div style="font-weight: 700; color: #288bff; font-size: 40px; text-transform: uppercase; display: inline; ">
All Notifications (<%= @allnotifications.count %>)
</div>
<div style="font-weight: 700; color: #288bff; font-size: 20px; margin-left: 15px; display: inline; ">
<%= link_to "New Notifications", notifications_path(current_user), class: "blue" %>
</div>
</div>
</div>



<div class="width5-center">





<div id="products">
<%= render 'users/allnotifications' %>
</div>

<%= will_paginate @allnotifications %>


</div>

app/views/users/notifications.html.erb
<div style="background-color: rgba(51,51,51,0.1); padding: 25px 0px 30px 0px; line-height: 1;">
<div class="width7">
<div style="font-weight: 700; color: #288bff; font-size: 40px; text-transform: uppercase; display: inline; ">
Notifications
</div>
<div style="font-weight: 700; color: #288bff; font-size: 20px; margin-left: 15px; display: inline; ">
<%= link_to "All Notifications", allnotifications_path(current_user), class: "blue" %>
</div>
</div>
</div>



<div class="width7">





<% if notificationcount == 0 %>
 <div class="nonew-notifications">
  You don’t have any new notifications. When someone answers your question, replies to or recommends your answer, you'll see it here.
  </div>
<% end %>

<div class="width5-center">
<% @activities.each do |activity| %>	

  <%= render_activity activity %>	

<% end %>


</div>
</div>


<script>
$(document).ready(function() {
    $.ajax '/users/read_all_notifications' ,
        type: "post"
        dataType: "json"
        beforeSend: (xhr) ->
          xhr.setRequestHeader "X-CSRF-Token", $("meta[name=\"csrf-token\"]").attr("content")
        cache: false  // code here

 });
 
 </script>

app/views/users/questions.html.erb
<%= render 'users/userhead' %>

<div class="width6">


<div class="width30">
<div class="questionnavbar52user">
<%= link_to "Upvoted", user_path(@user) %>
</div>
</div>
<div class="width30">
<div class="questionnavbar50user">		
Questions
</div>
</div>
<div class="width30">
<div class="questionnavbar51user">	
<%= link_to "Answers", userinterviews_path(@user) %>
</div>
</div>

<% if @user.questions.count == 0 %>
<div class="center">
<div class="eventmargin2">
<%= @user.name %> hasn't asked any questions yet.
</div>
</div>
<% end %>

<% if @user.comments.count == 0 %>
<div class="center">
<div class="eventmargin2">
<%= @user.name %> hasn't asked any questions yet.
</div>
</div>
<% else %>
<div class="row"></div>
<div class="profilemargin">
</div>
<% end %>

<% @comments.each do |comment| %>

<div class="titlecontainer20">
<%= link_to (comment.title), post_comment_path(@post, comment) %>
</div>

<div class="nameblueside2">
<%= pluralize(comment.questions.count, 'Answer') %> 
</div>

<div class="date2">
Asked <%= time_ago_in_words(comment.created_at) %> ago
</div>

<hr/>


<% end %>

app/views/users/show.html.erb
<%= render 'profile_head' %>


<div class="navbar-profile-content-container">




</div>



<script>
$('#blue-edit-profile, .close-modal-slide, .modaldeclinebutton').click(function () {
        $('.fullpage-modal').toggle('slide', {
            direction: 'top'
        }, 300);
    });
</script>

app/views/users/show.js.erb
$('#products').append('<%= j render('users/show') %>');
<% if @questions.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@questions) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/users/upvotes.js.erb
$('#products').append('<%= j render('users/upvotes') %>');
<% if @questions.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@questions) %>');
<% else %>
  $('.pagination').remove();
<% end %>