config/routes.rb
Omrails::Application.routes.draw do
  

  
  
 post '/tinymce_assets' => 'tinymce_assets#create'

  get "profile/place"
  get "profile/bio"
  get "users/show"

resources :posts, :path => "news" do
   member do
    post "sort" => "comments#sort"
  end
   member do
    get 'question_form'
  end
   collection { post :sort }
  member do
      put :upvote
    end
    resources :events
  resources :comments, :path => "q" do
    member do
      put :upvote
      get :tag
    end
    member do 
      get :unansweredquestions
    end
  end 
  resources :pictures
end
      
resources :comments, :path => "q" do
    member do
      put :upvote
    end
    resources :questions, :path => "a" do
    member do
      put :upvote
    end
  end
end 

 resources :events do
 resources :articles
end

resources :questions, :path => "a" do
  member do
      put :upvote
    end
   resources :links do
    member do
      put :upvote
    end
  end
end

devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :omniauth_providers => [:twitter],
controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: :registrations, sessions: "sessions"}
   
  
  root to: 'posts#index'
  match '/about', to: 'pages#about',  via:'get'
  match '/contact', to: 'pages#contact',  via:'get'
  match '/guidelines', to: 'pages#guidelines',  via:'get'
  match '/tos', to: 'pages#tos',  via:'get'
  match '/browser', to: 'pages#browser',  via:'get'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'tags/:tag', to: 'posts#show'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/upvoted', to: 'users#upvoted', as: :upvoted
  get 'users/:id/userquestions', to: 'users#questions', as: :userquestions
  get 'users/:id/notifications', to: 'users#notifications', as: :notifications 
  get 'users/:id/allnotifications', to: 'users#allnotifications', as: :allnotifications 
  post 'users/read_all_notifications', to: 'users#read_all_notification', as: :read_all_notifications 
  get 'users/:id/upvotes', to: 'users#upvotes', as: :upvotes
  get 'users/:id/allanswers', to: 'users#allanswers', as: :allanswers
  get 'users/:id/allcomments', to: 'users#allcomments', as: :allcomments
  get 'news/:id/topquestions', to: 'posts#showtopquestion', as: :topquestions
  get 'news/:id/answersmore', to: 'posts#showanswersmore', as: :answersmore
  get 'news/:id/ordered', to: 'posts#ordered', as: :ordered
  get 'news/:id/new_posts', to: 'posts#new_posts', as: :new_posts
  get 'comments/:id/unpublished', to: 'comments#unpublished', as: :unpublished
  get '/admin', to: 'posts#admin', as: :admin
  get '/admin/questions', to: 'pages#admin_questions', as: :adminquestions
  get '/admin/answers', to: 'pages#admin_answers', as: :adminanswers
  get '/admin/replies', to: 'pages#admin_replies', as: :adminreplies
  get '/following', to: 'pages#following', as: :following
  get 'top', to: 'posts#top', as: :top
  get  '/image_form', to: 'posts#image_form', as: :image_form
  get  '/search-news', to: 'posts#search', as: :search

   devise_scope :user do
    get "/info" => "registrations#info"
  end

  get '*path' => redirect('/')

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
 extend FriendlyId
  friendly_id :body, use: :slugged

belongs_to :question, counter_cache: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
   @post = Post.friendly.find params[:post_id]
   @comments = @post.comments
   @links = @post.links.order(:created_at).limit(5)
   @questions = @post.questions.order("cached_votes_total desc")
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    
  @question = Question.friendly.find(params[:question_id]) 
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @skip_footer = true
    
    @answer = Answer.new(answer_params)
    @question = Question.friendly.find(params[:question_id])
    
    
    
    respond_to do |format|
      if @answer.save
        format.html { redirect_to post_comment_path(@question.comment.post, @question.comment) + "#question_#{@question.id.to_s}", notice: 'Answer posted' }
        
      else
        redirect_to root_path
        
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to :back, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body, :question_id, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%=div_for(answer) do %>

 	<%= answer.body %>

 	<% end %>

app/views/answers/_form.html.erb
<%= simple_form_for [@question, Answer.new] do |f| %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.input :body, as: :text, input_html: { rows: "1", class: "inputBody hello3" }, label: false,placeholder: "Answer" %>
<%= f.submit "Post", {  class: "myButton favouritebuttonleft" } %>
 <% end %>

app/views/answers/index.html.erb
<div class="visible-desktop hidden-phone hidden-tablet">

<div class="container">
 <div class="row">


<div class="span3">

<div class="commentimage2">
 <%= image_tag @post.image(:small) %>    
 </div>


<div class="info">
<div class="newspaper7"> 
<%= time_ago_in_words(@post.created_at) %> ago <br>
</div>
</div>

<div class="info">
<div class="newspaper7"> 
<strong><%= @post.country %></strong>
</div>
</div>

<hr/>

<div class="descriptioncontainer2">
<div class="newspaper7"> 
<%= @post.description %>
</div>
</div>

</hr>


<%= render 'links/link' %>

</div>




<div class="span7", style="padding-left: 30px;">

<div class="titlecontainer">
<%= @post.title %>
</div>


<hr />
<% if user_signed_in? %>
<div class="questioncontainer3">  
<%= link_to 'Ask Question', new_post_comment_path(@post), class: "button4" %>
</div>
<% else %>
<div class="questioncontainer3">  
<%= link_to 'Ask Question', new_user_registration_path, class: "button4" %>
</div>
<% end %>

<% if @post.comments.count == 1 %>
<div class="number2">
<strong><%= @post.comments.count %></strong> Question
</div>
<% else %>
<div class="number2">
<strong><%= @post.comments.count %></strong> Questions 
</div>
<% end %>

<div class="container">
<div class="row">
<div class="span6">
<% @questions.each do |question| %>

<div class="questionborder">
<div class="questioncontainer">
<%= link_to (question.comment.body), post_comment_questions_path(@post, @comment_id), class: "blue" %>
</div>
</div>

<div class="info2b">
<strong><%= question.user.name %></strong> <br>
</div>
<div class="blue">
<%= question.title %>
</div>
<hr/>

<%= question.body %>
<div class="lightcontainer6">
 
Flag -
Posted <%= time_ago_in_words(question.created_at) %> ago <br>
</div>

<% end %>

</div>
<div class="span2 offset1">
<div class="allquestions">
<%= link_to ("Questions"), post_path(@post), class: "blue" %>
</div>
<div class="allquestions2">
Top Answers
</div>
</div>
</div>
</div>
</div>

</div>
</div>
</div>
</div>



<div class="visible-phone visible-tablet">
<div class="span10">

<div class="commentimage">
  <%= image_tag @post.image %>    
 </div>

<div class="titlecontainer">
<%= @post.title %>
</div>

<div class="info">
<div class="newspaper7"> 
<%= time_ago_in_words(@post.created_at) %> ago <br>
</div>
</div>

<div class="info">
<div class="newspaper7"> 
<strong><%= @post.country %></strong>
</div>
</div>
<hr/>


<div class="descriptioncontainer2">
<div class="newspaper7"> 
<%= @post.description %>
</div>
<%= render 'links/link' %>
<hr/>
</div>



<% if user_signed_in? %>
<div class="questioncontainer3">  
<%= link_to 'Ask Question', new_post_comment_path(@post), class: "button4" %>
</div>
<% else %>
<div class="questioncontainer3">  
<%= link_to 'Ask Question', new_user_registration_path, class: "button4" %>
</div>
<% end %>

<% if @post.comments.count == 1 %>
<div class="number2">
<strong><%= @post.comments.count %></strong> Question
</div>
<% else %>
<div class="number2">
<strong><%= @post.comments.count %></strong> Questions 
</div>
<% end %>

<div id="pin" class="transitions-enabled">
<%= render 'comments/comment' %>
</div>




</div>
</div>

app/views/answers/new.html.erb
<%= render 'form' %>