config/routes.rb
Omrails::Application.routes.draw do
  

  
  
 post '/tinymce_assets' => 'tinymce_assets#create'

  get "profile/place"
  get "profile/bio"
  get "users/show"

resources :posts, :path => "news" do
   member do
    post "sort" => "comments#sort"
  end
   member do
    get 'question_form'
  end
   collection { post :sort }
  member do
      put :upvote
    end
    resources :events
  resources :comments, :path => "q" do
    member do
      put :upvote
      get :tag
    end
    member do 
      get :unansweredquestions
    end
  end 
  resources :pictures
end
      
resources :comments, :path => "q" do
    member do
      put :upvote
    end
    resources :questions, :path => "a" do
    member do
      put :upvote
    end
  end
end 

 resources :events do
 resources :articles
end

resources :questions, :path => "a" do
  member do
      put :upvote
    end
   resources :links do
    member do
      put :upvote
    end
  end
end

devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :omniauth_providers => [:twitter],
controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: :registrations, sessions: "sessions"}
   
  
  root to: 'posts#index'
  match '/about', to: 'pages#about',  via:'get'
  match '/contact', to: 'pages#contact',  via:'get'
  match '/guidelines', to: 'pages#guidelines',  via:'get'
  match '/tos', to: 'pages#tos',  via:'get'
  match '/browser', to: 'pages#browser',  via:'get'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'tags/:tag', to: 'posts#show'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/upvoted', to: 'users#upvoted', as: :upvoted
  get 'users/:id/userquestions', to: 'users#questions', as: :userquestions
  get 'users/:id/notifications', to: 'users#notifications', as: :notifications 
  get 'users/:id/allnotifications', to: 'users#allnotifications', as: :allnotifications 
  post 'users/read_all_notifications', to: 'users#read_all_notification', as: :read_all_notifications 
  get 'users/:id/upvotes', to: 'users#upvotes', as: :upvotes
  get 'users/:id/allanswers', to: 'users#allanswers', as: :allanswers
  get 'users/:id/allcomments', to: 'users#allcomments', as: :allcomments
  get 'news/:id/topquestions', to: 'posts#showtopquestion', as: :topquestions
  get 'news/:id/answersmore', to: 'posts#showanswersmore', as: :answersmore
  get 'news/:id/ordered', to: 'posts#ordered', as: :ordered
  get 'news/:id/new_posts', to: 'posts#new_posts', as: :new_posts
  get 'comments/:id/unpublished', to: 'comments#unpublished', as: :unpublished
  get '/admin', to: 'posts#admin', as: :admin
  get '/admin/questions', to: 'pages#admin_questions', as: :adminquestions
  get '/admin/answers', to: 'pages#admin_answers', as: :adminanswers
  get '/admin/replies', to: 'pages#admin_replies', as: :adminreplies
  get '/following', to: 'pages#following', as: :following
  get 'top', to: 'posts#top', as: :top
  get  '/image_form', to: 'posts#image_form', as: :image_form
  get  '/search-news', to: 'posts#search', as: :search

   devise_scope :user do
    get "/info" => "registrations#info"
  end

  get '*path' => redirect('/')

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base

has_attached_file :image, :styles => { :original => "30x30>" }
validates :image, presence: true

belongs_to :post
belongs_to :user
 

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @skip_footer = true 
    @post = Post.friendly.find(params[:post_id])
    @pictures = @post.pictures
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
     @post = Post.friendly.find(params[:post_id])
     @picture = Picture.find(params[:id])
  end

  # GET /pictures/new
  def new
    @post = Post.friendly.find(params[:post_id])
    render_forbidden and return unless can_edit?
    
  end

  # GET /pictures/1/edit
  def edit
    @skip_footer = true 
    @post = Post.friendly.find(params[:post_id])

  end

  # POST /pictures
  # POST /pictures.json
  def create
    @post = Post.friendly.find(params[:post_id])
    @picture = @post.pictures.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @post, notice: 'Picture posted.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    @post = Post.friendly.find(params[:post_id])
     @picture = Picture.find(params[:id])
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @post, notice: 'Picture updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

     def can_edit?
    current_user.try(:admin?) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image_file_name, :image_content_type, :image_file_size, :post_id, :user_id, :description, :image_remote_url, :image)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div class="infopage-container-modal">
<div class="guidelines-text-light" style="color: #018bc6 !important; font-size: 14px; float: left;">
Add Image
</div>

<hr class="modalline-slide" style="margin-top: 10px;"/>

 <% if user_signed_in? %>

<%= simple_form_for([@post, Picture.new]) do |f| %>
<%= f.hidden_field :user_id, :value => current_user.id %>




<i class="fa fa-picture-o" style="margin: 0px; margin-right: 15px; font-size: 28px; display: block; margin: 0 auto; color: #f99625; position: absolute;"></i>
<%= f.input :image, input_html: { :style => "opacity:0;" }, label: false %>
<img id="blah2" style="margin-bottom: 0px; background-color: rgba(51,51,51,0.03) !important;"/>

<hr class="modalline-slide"/>



<div class="row"></div>
<%= f.submit "Add", class: "submitbluemodal" %>




<div class="guidelines-text-light">
Please make sure you own the rights to the image.
    </div>



  <% end %>

  <% else %>

Please <%= link_to "Login", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %> to add an image.


<% end %> 

</div>


<script>
function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#blah2').attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $("#picture_image").change(function(){
        readURL(this);
    });

</script>

app/views/pictures/_picture.html.erb
<div class="box2">
  
    <%= image_tag picture.image(:medium) %>
   <strong><p class="description">
        <%= picture.description %>
    </p></strong>
    
</div>

app/views/pictures/edit.html.erb
<div class="settingsnavtop">

<div class="width6">
<div class="underpodiumhomeguidelinesbig" style="color: white; display: inline;">
Change Image
</div>
</div>

<div class="absoluteheader">
<%= render 'layouts/xheader' %>
</div>

</div>



<div class="width6">
<div class="sixty"></div>
 <% if user_signed_in? %>

<%= simple_form_for([@post, @picture]) do |f| %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<div class="blah2">
<div class="addimageevent">
<%= f.input :image, input_html: { :style => "opacity:0;" }, label: false %>
</div>
</div>
<img id="blah2" style="margin-bottom: 0px; background-color: rgba(51,51,51,0.03) !important;"/>

<div class="floatright">
<%= f.submit "Add Image", class: "modalacceptbutton", style: "margin-bottom: 30px;" %>
</div>




  <% end %>

  <% else %>

Please <%= link_to "Login", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %> to add an image.


<% end %> 


<script>
function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#blah2').attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $("#picture_image").change(function(){
        readURL(this);
    });

</script>
</div>

app/views/pictures/index.html.erb
<div class="settingsnavtop" style="margin-bottom: -1px;">
<div class="width6">

<div class="underpodiumhomeguidelinesbig" style="color: white; display: inline;">
Image for <strong><%= link_to (@post.title), post_path(@post), class: "white" %></strong>
</div>
</div>
<div class="absoluteheader">
<%= render 'layouts/xheader' %>

</div>
</div>

<div class="row"></div>


<style media="screen">
  .experiment { background-image:  url(<%= @post.pictures.first.image %>); background-color: #333; }
  </style>
<div class="experiment">
<div class="darker"></div>
<%= link_to "Change/Delete Image", edit_post_picture_path(@post, @post.pictures.first), class: "white", style: "margin: 40px; background-color: rgba(255,255,255,0.3); font-size: 12px; font-weight: bold; padding: 10px; position: absolute;" %>
</div>



<div class="padding10"></div>
<div class="center">


<div class="width6">
<div class="eventmargin3">
Image uploaded by <strong><%= link_to (@post.pictures.first.user.name), user_path(@post.pictures.first.user) %></strong>
</div>
</div>
</div>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<%= image_tag @picture.image %>