config/routes.rb
Omrails::Application.routes.draw do
  

  
  
 post '/tinymce_assets' => 'tinymce_assets#create'

  get "profile/place"
  get "profile/bio"
  get "users/show"

resources :posts, :path => "news" do
   member do
    post "sort" => "comments#sort"
  end
   member do
    get 'question_form'
  end
   collection { post :sort }
  member do
      put :upvote
    end
    resources :events
  resources :comments, :path => "q" do
    member do
      put :upvote
      get :tag
    end
    member do 
      get :unansweredquestions
    end
  end 
  resources :pictures
end
      
resources :comments, :path => "q" do
    member do
      put :upvote
    end
    resources :questions, :path => "a" do
    member do
      put :upvote
    end
  end
end 

 resources :events do
 resources :articles
end

resources :questions, :path => "a" do
  member do
      put :upvote
    end
   resources :links do
    member do
      put :upvote
    end
  end
end

devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :omniauth_providers => [:twitter],
controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: :registrations, sessions: "sessions"}
   
  
  root to: 'posts#index'
  match '/about', to: 'pages#about',  via:'get'
  match '/contact', to: 'pages#contact',  via:'get'
  match '/guidelines', to: 'pages#guidelines',  via:'get'
  match '/tos', to: 'pages#tos',  via:'get'
  match '/browser', to: 'pages#browser',  via:'get'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'tags/:tag', to: 'posts#show'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/upvoted', to: 'users#upvoted', as: :upvoted
  get 'users/:id/userquestions', to: 'users#questions', as: :userquestions
  get 'users/:id/notifications', to: 'users#notifications', as: :notifications 
  get 'users/:id/allnotifications', to: 'users#allnotifications', as: :allnotifications 
  post 'users/read_all_notifications', to: 'users#read_all_notification', as: :read_all_notifications 
  get 'users/:id/upvotes', to: 'users#upvotes', as: :upvotes
  get 'users/:id/allanswers', to: 'users#allanswers', as: :allanswers
  get 'users/:id/allcomments', to: 'users#allcomments', as: :allcomments
  get 'news/:id/topquestions', to: 'posts#showtopquestion', as: :topquestions
  get 'news/:id/answersmore', to: 'posts#showanswersmore', as: :answersmore
  get 'news/:id/ordered', to: 'posts#ordered', as: :ordered
  get 'news/:id/new_posts', to: 'posts#new_posts', as: :new_posts
  get 'comments/:id/unpublished', to: 'comments#unpublished', as: :unpublished
  get '/admin', to: 'posts#admin', as: :admin
  get '/admin/questions', to: 'pages#admin_questions', as: :adminquestions
  get '/admin/answers', to: 'pages#admin_answers', as: :adminanswers
  get '/admin/replies', to: 'pages#admin_replies', as: :adminreplies
  get '/following', to: 'pages#following', as: :following
  get 'top', to: 'posts#top', as: :top
  get  '/image_form', to: 'posts#image_form', as: :image_form
  get  '/search-news', to: 'posts#search', as: :search

   devise_scope :user do
    get "/info" => "registrations#info"
  end

  get '*path' => redirect('/')

  

end

app/models/post.rb
class Post < ActiveRecord::Base
extend FriendlyId
friendly_id :title, use: :slugged

has_attached_file :image, :styles => { :small => "300x300>", :thumb => "38x" }


def body_format
  self.body.gsub(/<p>.<\/p>/,"")
end

scope :topcategory, where(:category => true)
scope :nothiddencategory, where(:category => false).where(:hide => false)
scope :hiddencategory, where(:category => false).where(:hide => false).limit(3)
scope :top, (select('posts.*, count(comments.id) as count_comments')
             .joins("left join comments on comments.post_id = posts.id and comments.created_at >= '#{Time.zone.now.beginning_of_day}'")
             .group('posts.id')
             .order('count_comments desc'))



scope :published, where(:hide => true)


validates :user_id, presence: true
validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                             size: { less_than: 2.megabytes }

belongs_to :user
acts_as_votable
acts_as_taggable
has_many :comments, :dependent => :destroy
has_many :links, :dependent => :destroy
has_many :questions, :through => :comments, :dependent => :destroy
has_many :pictures, :dependent => :destroy
has_many :events, :dependent => :destroy
has_many :articles, through: :events, :dependent => :destroy
acts_as_list


def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


def upvote
@post = Post.friendly.find(params[:id])
@post.liked_by current_user
end

def search
end

def image_form

respond_to do |format|
  format.html
  format.js
 end
end 

def question_form
  @post = Post.friendly.find(params[:id])
respond_to do |format|
  format.html
  format.js
 end
end 

  # GET /posts
  # GET /posts.json
  def index
   @category_header = true 
  @skip_bottom = true  
  @top_stories_none = true 
  
if params[:tag]
@posts = Post.where(:hide => true).tagged_with(params[:tag]).order("created_at desc").page(params[:page]).per_page(3)
@hidden = Post.hiddencategory.order("created_at desc").tagged_with(params[:tag]) 
else
@toppost = Post.where(:hide => true).order("position").limit(1)
@posts = Post.where(:hide => true).order("position").offset(1).limit(2)
@homepage_answers = Question.where(:hide => true, :recommend => true).limit(1)


end

respond_to do |format|
  format.html
  format.js
 end
end
    
 

  # GET /posts/1
  # GET /posts/1.json
  def show
   @image_bottom = true 
  @post = Post.friendly.find(params[:id])
  @answersmore = @post.questions.where(:hide => true, :recommend => false).order('cached_votes_total desc').limit(3)
  @ordered = @post.questions.where(:hide => true, :recommend => true).order("position")
  @answers = @post.questions.where(:hide => true)
  @questions = @post.comments.where(:published => true)
  @comments = @post.comments.where(:published => true).order('position').page(params[:page]).per_page(3)
  @answers = @post.questions.page(params[:page]).per_page(3)
  @articles = @post.articles.order("created_at desc").limit(5)
  @comment = Comment.new
  @events = @post.events.order("created_at desc").limit(2)
  @related = @post.find_related_tags
  @media = @post.comments.where(:active => true).order("created_at desc").limit(2)
  end


  def admin
  @skip_footer = true 
  @posts = Post.where(:hide => true).order("position")
 end

 def sort
  params[:post].each_with_index do |id, index|
    Post.update_all({position: index+1}, {id: id})
  end
  render nothing: true
end


    def ordered
    render_forbidden and return unless can_edit?
  @post = Post.friendly.find(params[:id])
  @ordered = @post.comments.where(:published => true).order("position")
  @comment = Comment.new
  end


  def new_posts
  render_forbidden and return unless can_edit?
  @post = Post.friendly.find(params[:id])
  @new_posts = @post.comments.where(:published => false).order("created_at desc")
  @comment = Comment.new
  end

  def showanswersmore
  @skip_footer = true  
  @post = Post.friendly.find(params[:id])
  @questions = @post.questions.where(:hide => true, :recommend => false).order('cached_votes_total desc').page(params[:page]).per_page(2)
  @comment = Comment.new
  end

  def showtopquestion
  @skip_footer = true 
  @post = Post.friendly.find(params[:id])
  @comments = @post.comments.order('comments.questions_count desc').page(params[:page]).per_page(2)
  @comment = Comment.new 

end

  # GET /posts/new
  def new
    @skip_footer = true 
    render_forbidden and return unless can_edit?
    @posts = Post.all
    @post = current_user.posts.new
    
  end

  # GET /posts/1/edit
  def edit
    @skip_footer = true 
    render_forbidden and return unless can_edit?
 @post = Post.friendly.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    render_forbidden and return unless can_edit?
    @post = current_user.posts.new(post_params)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    render_forbidden and return unless can_edit?
   @post = Post.friendly.find(params[:id])
   
   respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        redirect_to root_path
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Story deleted'  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def can_edit?
  current_user.try(:admin?) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, :image_remote_url, :title, :country, :tag_list, :link, :domain, :top, :hide, :category, :event)
    end
end



  

app/helpers/posts_helper.rb
module PostsHelper
 
 def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end




end

app/views/posts/_articles.html.erb
<div class="row"></div>
<hr class="dividerline"/>
<div class="dividerhead">
FURTHER READING
</div>

<% @articles.each_with_index do |article, i| %>
<div class="articletitle">
<%= link_to (article.title), url_for(article.link), :target => "_blank", class: "blue" %>
</div>
<div>
<%= link_to (article.domain), url_for(article.link), :target => "_blank", class: "readmore", style: "color: #333 !important; opacity: 0.5; float: left;" %>
</div>

<div class="row"></div>

<% unless (i + 1) == @articles.count  %>
<hr class="linksline" style="float: none; margin-top: 15px; margin-bottom: 15px; width: 15%;"/>
<% end %>


<% end %>

app/views/posts/_categories.html.erb
<% if request.path == '/' %>	
<div class="margin-c-dark">
Top Stories
</div>
<% else %>
<%= link_to 'Top Stories', root_path, class: "margin-c" %>
<% end %>



<% if request.path == '/tags/world' %>		
<div class="margin-c-dark">
World
</div>
<% else %>
<a href="/tags/world" class="margin-c"  >World</a>
<% end %>


<% if request.path == '/tags/united-states' %>		
<div class="margin-c-dark">
U.S.
</div>
<% else %>
<a href="/tags/united-states" class="margin-c"  >U.S.</a>
<% end %>


<% if request.path == '/tags/politics' %>		
<div class="margin-c-dark">
Politics
</div>
<% else %>
<a href="/tags/politics" class="margin-c"  >Politics</a>
<% end %>

<% if request.path == '/tags/business' %>		
<div class="margin-c-dark">
Business 
</div>
<% else %>
<a href="/tags/business" class="margin-c"  >Business</a>
<% end %>

<% if request.path == '/tags/technology' %>		
<div class="margin-c-dark">
Technology
</div>
<% else %>
<a href="/tags/technology" class="margin-c" >Technology</a>
<% end %>

<% if request.path == '/tags/science' %>		
<div class="margin-c-dark">
Science
</div>
<% else %>
<a href="/tags/science" class="margin-c"  >Science</a>
<% end %>

app/views/posts/_followers.html.erb
<div class="right-element-container">
<div class="small-dividerhead">
Followers
</div>

<% @post.votes.by_type(User).limit(3).voters.each do |user| %>
  <div class="follower-avatar-border" style="margin-left: 0px;">
  <div class="follower-image">
<%= image_tag user.image %>
</div>
</div>
  <div class="follower-avatar-border">
  <div class="follower-image">
<%= image_tag user.image %>
</div>
</div>
<% end %>

<div class="row"></div>

</div>

<div class="row"></div>

app/views/posts/_form.html.erb
<style media="screen">
  #blah2 { background-image: '#blah2'); background-color: #333;  background-size: cover;
    background-repeat: no-repeat;
    background-position: center; }
</style>



   <%= simple_form_for @post, url: posts_path do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

<div class="width6">



<%= f.input :title, as: :text, input_html: { rows: "1", :class => "eventformtitlelarge", :style => "font-size: 34px;" }, label: false ,placeholder: "Title" %>
<%= f.input :description, as: :text, input_html: { :class => "eventformbody" }, label: false ,placeholder: "Description" %>
<div class="row"></div>

<div class="blah2">
<div class="addimageevent2">
<%= f.input :image, input_html: { :style => "opacity:0;" }, label: false %>
</div>
</div>
<img id="addnewslogo"/>

<%= f.input :domain, as: :text, input_html: { :class => "eventformlink" }, label: false ,placeholder: "www.example.com" %>
<%= f.input :link, as: :text, input_html: { :class => "eventformlink", :style => "width: 98% !important;" }, label: false ,placeholder: "www.example.com/123abc" %>

<div class="row"></div>
<hr/>

<div class="row"></div>

<%= f.input :tag_list, as: :text,  input_html: { rows: "1", :class => "taglistform" }, label: false, placeholder: "World, Politics, Technology, Business, Science" %>

<div class="checkboxcover">
<a id="close">
<%= f.check_box :hide, as: :boolean, input_html: { :class => "buttoncheckbox" }, label: false %>
</a>
<div class="buttoncheckbox2">
Publish to homepage
  </div>
</div>

<div class="checkboxcover">
<%= f.check_box :category, as: :boolean, input_html: { :class => "buttoncheckbox" }, label: false %>
<div class="buttoncheckbox2">
Featured on category page
</div> 
</div>

<% if @post.events.present? %>
<div class="checkboxcover">
<%= f.check_box :event, as: :boolean, input_html: { :class => "buttoncheckbox" }, label: false %>
<div class="buttoncheckbox2">
Show latest event for post
</div> 
</div>
<% end %>

<div class="row"></div>

<hr style="margin-top: 35px;"/>

<%= f.submit "Publish", class: "submitblueinfo", style: "float: right;" %>

</div>

 <% end %>




<script>
function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#addnewslogo').attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $("#post_image").change(function(){
        readURL(this);
    });

</script>

app/views/posts/_hiddencategory.html.erb
<% @hidden.each do |post| %>

<style media="screen">
  .experimentstrip-<%= post.id %> { background-image: url(<%= post.image %>); }
</style>

<%= link_to post_path(post) do %> 

<div class="experimentstrip-<%= post.id %>" style="position: relative; width: 100%;
  height: 340px; background-size: cover;
    background-repeat: no-repeat;
    background-position: center; margin-bottom: 0px;">


<div class="darker"></div>


<div class="absolutecontainer">
<div class="relativecontainer">
<%= link_to (post.title), post_path(post), class: "posttext" %> 

<div class="descriptionmarginstripsmall hidden-phone"> 
<%= truncate(post.description, length: 300, separator: ' ') %>
</div>

<div class="descriptionmarginstripsmall hidden-tablet hidden-desktop"> 
<%= truncate(post.description, length: 100, separator: ' ') %>
</div>

</div>
</div>
</div>


<% end %>



<div class="width6">

<div class="questionoutline">
<div class="mobilepadding20"></div>

<% if post.questions.count > 0 %>
<div class="topanswershome">
Top Answers
</div>
<div class="topanswershome">
<%= link_to "Top Questions", topquestions_path(post), class: "navbarlink" %>
</div>
<div class="topanswershome">
<%= link_to "New Questions", newquestions_path(post), class: "navbarlink" %>
</div>
<hr class="topquestion"/>
<% else %>

<div class="topanswershomenone">
There are no answers yet. 
</div>
<div class='center'>
<%= link_to "See questions...", topquestions_path(post), class: "seeallleft" %>
</div>

<% end %>


<% post.questions.order('cached_votes_total desc').limit(3).each do |question, i| %>


<div class="experimentname">
<strong><%= link_to (question.user.name), user_path(question.user) %></strong> 
<% if question.title.present? %>
 | <%= truncate(question.title, :separator => ' ', length: 55) %>
<% end %>
</div>  

<div class="row"></div>

<div class="titlecontainer30">
<%= link_to (question.comment.title), post_comment_path(question.comment.post, question.comment) %>

</div>


<div class="p2">  
 
    <%= truncate(question.body, :separator => ' ', length: 120) %>
    <%= link_to ("Read More"), comment_question_path(question.comment, question), class: "readmore"  %>

</div>

<hr class="topquestion"/>

<% end %>

<% unless post.questions.count == 0 %>
<div class='center'>
<%= link_to "See all...", post_path(post), class: "seeallleft" %>
</div>
<% end %>


<hr class="homebuttonline"/>


</div>




</div>



<% end %>

app/views/posts/_media.html.erb
<div class="right-element-container">
<div class="small-dividerhead">
Media
</div>

<% @media.each do |comment| %>

<div class="media-layout">
<%= image_tag comment.image %>
</div>

<% end %>


</div>

<div class="row"></div>

app/views/posts/_mobilecategories.html.erb
<div class="width10">
<div class="mobilecategory">
<% if params[:tag] %>
<%= params[:tag].capitalize %> 
<% else %>
Top Stories
<% end %>
</div>


<div class="allcategory">
Categories...
</div>

<div class="allcategoriesmobile" style="display: none;">
<hr class="mobilecategorieshr"/>

<% if request.path == '/' %>	
<div class="mobilecategoriesboxfaded">
Top Stories
</div>
<% else %>
<div class="mobilecategoriesbox">
<%= link_to "Top Stories", root_path, style: "text-decoration: none !important;", class: "hoverbluemobile" %>
</div>
<% end %>

<% if request.path == '/tags/world' %>		
<div class="mobilecategoriesboxfaded">
World
</div>
<% else %>
<div class="mobilecategoriesbox">
<a href="/tags/world" style=" text-decoration: none !important;" class="hoverbluemobile"  >World</a>
</div>
<% end %>

<% if request.path == '/tags/politics' %>		
<div class="mobilecategoriesboxfaded">
Politics
</div>
<% else %>
<div class="mobilecategoriesbox">
<a href="/tags/politics" style=" text-decoration: none !important;" class="hoverbluemobile"  >Politics</a>
</div>
<% end %>

<% if request.path == '/tags/business' %>		
<div class="mobilecategoriesboxfaded">
Business
</div>
<% else %>
<div class="mobilecategoriesbox">
<a href="/tags/business" style=" text-decoration: none !important;" class="hoverbluemobile"  >Business</a>
</div>
<% end %>

<% if request.path == '/tags/technology' %>		
<div class="mobilecategoriesboxfaded">
Technology
</div>
<% else %>
<div class="mobilecategoriesbox">
<a href="/tags/technology" style=" text-decoration: none !important;" class="hoverbluemobile"   >Technology</a>
</div>
<% end %>

<% if request.path == '/tags/science' %>		
<div class="mobilecategoriesboxfaded">
Science
</div>
<% else %>
<div class="mobilecategoriesbox">
<a href="/tags/science" style=" text-decoration: none !important;" class="hoverbluemobile"   >Science</a>
</div>
<% end %>

</div>


<div class="mobile20"></div>

</div>




<script>

    $(document).ready(function() {
        $('.allcategory').click(function() {
                $('.allcategoriesmobile').show();
               
                
        });
    }); 

</script>

app/views/posts/_orderedanswers.html.erb
<ul id="comments" data-update-url="<%= sort_post_path(@post) %>">
<% @ordered.each do |comment| %>
<%= content_tag_for :li, comment do %>

<span class="handle">+</span>
<div class="dragborder">
<div class="row"></div>
<div style="margin-top: 10px;"></div>



<%= render :partial => "layouts/#{comment.feed}_post", locals: {comment:comment} %>


    </div>
  <% end %>
<% end %>
</ul>

app/views/posts/_questions_banner.html.erb
<div class="grey-banner">

<div class="width5-center capital-title">
Questions
</div>	
<div class="width5-center">


<div class="question-banner-contain">

</div>

<% @questions.each do |question| %>

<div class="question-banner-contain">
<%= question.title %>
</div>


<% end %>

<div class="row"></div>


</div>
</div>

app/views/posts/_submitpost.html.erb
<% if user_signed_in? %>





<div id="choose-post-circles">

<hr/>

<div style="width: 49%; display: inline-block;">
<%= link_to new_post_comment_path(@post) do %>
<div class="add-post-icon-text">Aa</div>
<% end %>
</div>


<div style="width: 50%; display: inline-block;">
<i class="material-icons add-post-icon" id='text-icon-click'>question_answer</i>
</div>

</div>



<div class="row"></div>






<div id="text-form" style="display: none;">
<%= render 'comments/form' %>
</div>



<% else %>

<div class="interstitial-signin">

<div class="interstitial-text">
Sign in with Twitter to add to the story.
</div>

<div style="float: right">

<%= link_to user_omniauth_authorize_path(:twitter) do %>  
<div class="interstitial-button">
<i class="fa fa-twitter" style="color: #0076bc; font-size: 16px; display: inline-block; margin-bottom: 0px; margin-right: 2px;"></i>
Sign In
</div>
<% end %>
</div>
</div>
<% end %>





<script>
$("#plus-post").click(function(){
    $("#choose-post-circles").show();
    $(".left-40").hide();
    $("#plus-post").hide();
    
});

$("#text-icon-click").click(function(){ 
	$("#choose-post-circles").hide();
	$("#text-form").show();
});



$("#cancel").click(function(){
    $(".plus-post-buttons").hide();
    $(".left-40").show();
    $(".interstitial-left").show();
    $("#add-fact").hide();
});




</script>

app/views/posts/_timeline.html.erb
<div class="width5-center-large">
<div class="grey-banner">



<div class="capital-title">
Latest Events
</div>

<% @events.each do |event| %>
<%= link_to post_event_path(event.post, event) do %>
<div class="event-container">

<div class="event-image-thumb" style="background-image: url(<%= event.image %>)"></div>


<div class="event-title">
<%= event.title.titleize %>
</div>
<div class="event-description-light">
<%= event.body[0..100] %>
</div>


</div>

<% end %>
<% end %>

<div class="row"></div>



<% if @post.events.count > 1 %>
<%= link_to "ALL #{@post.events.count} EVENTS", post_events_path(@post), class: "capital-title-link" %>
 <% end %>

</div>



</div>

app/views/posts/index.html.erb
<% if params[:tag] %>

<%= params[:tag] %>


<% end %>

app/views/posts/ordered.html.erb
<div class="width7">
<div class="sixty"></div>
<div class="story-large-title">
<%= @post.title %>
</div>


<hr style="margin-bottom: 20px; margin-top: 20px;"/>



<div class="width5">

  
<div class="row"></div>


<%= render 'posts/orderedanswers' %>

</div>
</div>